<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admins-MacBook-Air-30.local" failures="1" tests="10" name="com.fairplay.test.WithdrawalNegativeTestCases" time="250.433" errors="0" timestamp="2023-06-12T16:02:28 IST" skipped="0">
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="login" time="43.565"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="checkAccessTokenAfterLogin" time="0.016"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdraw" time="4.890"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdrawForWrongOTP" time="25.799"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdrawForOTPLessThan6Digit" time="29.384"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdrawForOTPContainsOnlyLetters" time="41.086"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdrawForInvalidCred" time="27.932"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="verifyWithdrawForInvalidIFSC" time="32.059"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="logout" time="45.691"/>
  <system-out/>
  <testcase classname="com.fairplay.test.WithdrawalNegativeTestCases" name="checkAccessTokenAfterLogout" time="0.011">
    <failure message="The following asserts failed:
	expected [Not Able To Enter OTP..!!!] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Not Able To Enter OTP..!!!] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.fairplay.test.WithdrawalNegativeTestCases.checkAccessTokenAfterLogout(WithdrawalNegativeTestCases.java:147)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkAccessTokenAfterLogout -->
  <system-out/>
</testsuite> <!-- com.fairplay.test.WithdrawalNegativeTestCases -->
